--- 
cluster_config: 
  cluster_name: dcos-vagrant
  bootstrap_url: http://boot.dcos
  exhibitor_storage_backend: zookeeper
  exhibitor_zk_hosts: boot.dcos:2181
  exhibitor_zk_path: /zk-shared
  master_discovery: static
  master_list: 
  - 192.168.65.90
  resolvers:
  - 8.8.8.8
ssh_config: #req in master, optional jira DCOS-4455
  log_directory: /genconf/logs #req in CM.5, optional in master
  ssh_port: 22
  ssh_user: vagrant
  target_hosts: []
